In [1]:
import numpy as np

In [2]:
a=np.array([[4,6],[7,8],[9,1]])
ai=np.array([[4,6],[7,8],[9,1]])

print(a,"\n\n")
print(  a.ndim)  #checking dimention



[[4 6]
 [7 8]
 [9 1]] 


2


In [3]:
print( a[1,0],"\n\n") #indexing

print( a.dtype,"\n\n") #checking dimention


7 


int64 




In [4]:
print(  a.shape,"\n\n")

na = a.reshape(-1)  #flataning/reshaping/changing dimention

print( na,"\n\n")



(3, 2) 


[4 6 7 8 9 1] 




In [5]:
arrrr= na.reshape(2,3)

print( arrrr,"\n\n")

aii = np.concatenate((a, ai), axis=1)


[[4 6 7]
 [8 9 1]] 




In [7]:

for x in aii:
  for y in x:
    print( y)



4
6
4
6
7
8
7
8
9
1
9
1


In [8]:
print( np.sort(aii))


[[4 4 6 6]
 [7 7 8 8]
 [1 1 9 9]]


In [9]:
print( aii[0:2, 2])


[4 7]


In [11]:
newa =aii.reshape(-1)
print( np.sort(newa,))


[1 1 4 4 6 6 7 7 8 8 9 9]


In [12]:
ne = newa.copy()
newa[0] = 42
print( newa,"\n")
print(ne)


[42  6  4  6  7  8  7  8  9  1  9  1] 

[4 6 4 6 7 8 7 8 9 1 9 1]


In [13]:
ne = newa.view()
newa[0] = 42
print(newa,"\n")
print(ne,"\n")



[42  6  4  6  7  8  7  8  9  1  9  1] 

[42  6  4  6  7  8  7  8  9  1  9  1] 



In [14]:
print( newa[1:10:2])
newarr = newa.reshape(2, 3, 2)
print( newarr)
print( newarr.ndim)

[6 6 8 8 1]
[[[42  6]
  [ 4  6]
  [ 7  8]]

 [[ 7  8]
  [ 9  1]
  [ 9  1]]]
3


In [6]:

print( aii,"\n\n")

for x in a:
  print(x)
print("\n")


[[4 6 4 6]
 [7 8 7 8]
 [9 1 9 1]] 


[4 6]
[7 8]
[9 1]




In [ ]:
ar=np.array([[[1,2,3],[4,5,6]], [[9,8,7],[4,7,9]]])
print(ar)
print(ar.ndim)
print(ar[1,1,1])


[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [4 7 9]]]
3
7


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]
